---
- name: "Configure gitea"
  become: true
  ansible.builtin.template:
    src: gitea.ini.j2
    dest: "{{ gitea_configuration_path }}/gitea.ini"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 0600
  notify: "Restart gitea"

- name: "Service gitea"
  become: true
  ansible.builtin.systemd:
    name: gitea
    state: started
    enabled: true
  when: ansible_service_mgr == "systemd"
