---
- name: Create directory for custom logos
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: 'u=rwX,g=rX,o='
  with_items:
    - "{{ gitea_custom }}/public"
    - "{{ gitea_custom }}/public/img"

- name: Transfer custom logo.svg
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_logosvg) }}"
    dest: "{{ gitea_custom }}/public/img/logo.svg"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0644'
  tags: skip_ansible_lint
  ignore_errors: true

- name: Transfer custom logo.png
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_logopng) }}"
    dest: "{{ gitea_custom }}/public/img/logo.png"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0644'
  tags: skip_ansible_lint
  ignore_errors: true

- name: Transfer custom favicon.png
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_faviconpng) }}"
    dest: "{{ gitea_custom }}/public/img/favicon.png"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0644'
  tags: skip_ansible_lint
  ignore_errors: true

- name: Transfer custom apple-touch-icon.png
  become: true
  ansible.builtin.copy:
    src: "{{ lookup('first_found', transfer_custom_logo_appletouchiconpng) }}"
    dest: "{{ gitea_custom }}/public/img/apple-touch-icon.png"
    owner: "{{ gitea_user }}"
    group: "{{ gitea_group }}"
    mode: '0644'
  tags: skip_ansible_lint
  ignore_errors: true
