---
- name: Perform optional versionscheck
  ansible.builtin.include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: Gather installed packages for checks later on
  ansible.builtin.package_facts:
    manager: auto

- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ lookup('first_found', gitea_variables) }}"

- name: Gather versioning information
  ansible.builtin.include_tasks: set_version.yml

- name: Backup gitea before update
  ansible.builtin.include_tasks: backup.yml
  when: gitea_backup_on_upgrade|bool

- name: Create gitea user and role
  ansible.builtin.include_tasks: create_user.yml

- name: Install or update gitea
  ansible.builtin.include_tasks: install.yml

- name: Create directories
  ansible.builtin.include_tasks: directory.yml

- name: Setup gitea systemd service
  ansible.builtin.include_tasks: install_systemd.yml
  when: ansible_service_mgr == "systemd"

- name: Generate JWT Secrets if undefined
  ansible.builtin.include_tasks: jwt_secrets.yml

- name: Generate gitea secrets if undefined
  ansible.builtin.include_tasks: gitea_secrets.yml

- name: Configure gitea
  ansible.builtin.include_tasks: configure.yml

- name: Deploy optional fail2ban rules
  ansible.builtin.include_tasks: fail2ban.yml
  when: gitea_fail2ban_enabled|bool

- name: Optionally customize gitea
  ansible.builtin.include_tasks: customize_logo.yml
  when: gitea_customize_logo|bool

- name: Optionally customize footer
  ansible.builtin.include_tasks: customize_footer.yml
  when: gitea_customize_footer|bool

- name: Optionally deploy public files
  ansible.builtin.include_tasks: customize_public_files.yml
  when: gitea_customize_files|bool
