{
 "title": "admin connections",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Administration",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Administration actions\n\nTrack who connected to the admin interface of equipment"
   }
  },
  {
   "title": "FortiGate",
   "type": "logs",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "{host=\"fortigate.donk.lan\"} |= `Administrator`"
    }
   ]
  },
  {
   "title": "Pfsense",
   "type": "logs",
   "description": "Administration operations",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{hostname=\"pfsense.donk.lan\", application=\"php-fpm\"} |= ``"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "logs",
   "description": "Admin connection to vms",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{job=\"authlog\"} |= ``"
    }
   ]
  }
 ]
}