---
name: Ansible Lint check

# yamllint disable-line rule:truthy
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v3

      - name: 'Lint Ansible Playbook'
        uses: ansible/ansible-lint-action@v6
        with:
          targets: "."
