---
name: 'Yamllint GitHub Actions'

# yamllint disable-line rule:truthy
on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v3

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_file_or_dir: '.'
          yamllint_config_filepath: './.yamllint'
